// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPomMDj2S9ydQDcTpN8faRixDLcw6XJBY',
    appId: '1:766666935839:web:e82bb597a6ccdf63120f2a',
    messagingSenderId: '766666935839',
    projectId: 'jurapp-1f662',
    authDomain: 'jurapp-1f662.firebaseapp.com',
    storageBucket: 'jurapp-1f662.firebasestorage.app',
    measurementId: 'G-V6PR858DR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32tQI7TS-ZerdD2qD9z0o9uGGde2mPT4',
    appId: '1:766666935839:android:bdf9b1cc2d1ea9af120f2a',
    messagingSenderId: '766666935839',
    projectId: 'jurapp-1f662',
    storageBucket: 'jurapp-1f662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXbzzgRPIrU5rIMMg52O0Yqclcu0564E',
    appId: '1:766666935839:ios:71d5227c8c2fdd0d120f2a',
    messagingSenderId: '766666935839',
    projectId: 'jurapp-1f662',
    storageBucket: 'jurapp-1f662.firebasestorage.app',
    iosBundleId: 'com.example.jura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqXbzzgRPIrU5rIMMg52O0Yqclcu0564E',
    appId: '1:766666935839:ios:71d5227c8c2fdd0d120f2a',
    messagingSenderId: '766666935839',
    projectId: 'jurapp-1f662',
    storageBucket: 'jurapp-1f662.firebasestorage.app',
    iosBundleId: 'com.example.jura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPomMDj2S9ydQDcTpN8faRixDLcw6XJBY',
    appId: '1:766666935839:web:9ed73da2f259a915120f2a',
    messagingSenderId: '766666935839',
    projectId: 'jurapp-1f662',
    authDomain: 'jurapp-1f662.firebaseapp.com',
    storageBucket: 'jurapp-1f662.firebasestorage.app',
    measurementId: 'G-LK5DBN21S3',
  );
}
